name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag:1 }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${${{ $RELEASE_VERSION }}:1}
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: list of docker images
      run: docker images


- Your workflow file was invalid: The pipeline is not valid.
.github/workflows/dockerimage.yml (Line: 20, Col: 12): Unexpected symbol: 'tag:1'.
Located at position 20 within expression: steps.vars.outputs.tag:1,.github/workflows/dockerimage.yml (Line: 24, Col: 12): Unexpected symbol: '$RELEASE_VERSION:1'.
Located at position 1 within expression: $RELEASE_VERSION:1
View more details on GitHub Actions