name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      RELEASE_VERSION: ${GITHUB_REF:10}

    steps:
    - uses: actions/checkout@v1
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Check output
      run: |
        echo $RELEASE_VERSION
        echo ${RELEASE_VERSION:1}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${RELEASE_VERSION:1}
    - name: list of docker images
      run: docker images


- Your workflow file was invalid: The pipeline is not valid.
.github/workflows/dockerimage.yml (Line: 13, Col: 24): Unrecognized named-value: 'steps'.
Located at position 1 within expression: steps.vars.outputs.tag
View more details on GitH
