name: Docker Image CI

on: [push, tags]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: echo tag test
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: echo tag
      run: echo ${{ steps.tag.outputs.result }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
