name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

    steps:
    - uses: actions/checkout@v1
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Check output
      run: |
        echo $RELEASE_VERSION
        echo ${RELEASE_VERSION:1}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${RELEASE_VERSION:1}
    - name: list of docker images
      run: docker images
